### ISSUE TITLE
[question] status or maintainer?

### ISSUE THREAD

**Issue by TomasVotruba** [php-ug/php.ug#210]
Hey,
 
is any maintainer active here? From outside it looks like the project is dead, which is a pity.

- map is broken
- calendar is empty

I'd love to contribute to this project, make it fresh, nicer, PHP 7.1, Bootstrap 4 ready etc.
  
I already take care of PHP community in Czech: http://pehapkari.cz/, 

I found [an API](https://php-ug.github.io/php.ug/api/), that could help *me*, but I still want to give back.

**Comment by heiglandreas** [comment]
There is! :)

I just pinged you on salck, but the main question is: What do you mena by "map is broken" and "calendar is empty". Both work here; even with http…

Bringing the project to PHP 7.1 will be an [interesting task](https://php.ug/info.php): :wink:

But if you want to chime in with the new frontend, have a look at the new (currently empty) [frontent-project](https://github.com/php-ug/web.php.ug). The @php-ug/web-php-ug-team is in charge there…

**Comment by heiglandreas** [comment]
And the API will move over to api.php.ug when the new API is finished. But for the time being the endpoints will remain the same but might become extended so that editing is also possible via the API.

For more on that have a look at the [API-Project](https://github.com/php-ug/api.php.ug). The basic stuff is already available based on a Zend-Expressive 3 app. But I'm right in the middle of getting that up and running… ;)

**Comment by TomasVotruba** [comment]
So instead of merging year old PRs more and more unfinished projects pop-up? Why is that?

If I understand this correctly, I have to wait for some unfinished works (are there some PRs) on multiple Github repositories? How many maintainers there are? It looks like simple application at first sight

Add **map si broken**: I could not find meetups that I know of (Berlin), but after more looking into the page, I found there are groups displayed, not meetups (WTF). So I switched to meetups and see that there are many missing. That means broken for me. 

Add **calendar is broken**: there are no meetups till the end of year.

Maybe it works in some way, but I don't get it. It should be more clear, narrow and usable. I'd like to help with that :bird:

**Comment by heiglandreas** [comment]
There are multiple things. One is that moving to ZF 3 means a lot of work no one was really prepared to do. Im the end it turned out that it meant more or less a rewrite. And if tgat is nexessary then I'd ratger do it in a decent way. Mehmet wanted to do a frontend part and the main thing php.ug was missing all the time was a decent API. That was the reason why we split it up. It allows better and easier distribution of work. 

Apart from that the PHP usergroup in Berlin *Is* listed on php.ug the only thing that usergroup registered with the website was their twitter-handle. Everything else wasn't and still isn't added by them. As every usergroup owns their own data and decides what they want to share it's in their responsibility. And as they don't share a link to a calendar-file we can't display their next dates. Not like f.e. the PHP-usergroup in Frankfurt. 

So the website is not broken. It's that the usergroup didn't want to share that information.
That's the min oart of work tgat goes into the website. Finding usergroups, adding usergroups to the map, checking whether proposed entries match the criteria for a usergroup, archiving groups that seem not to be active anymore and much much more. 

optimizing the code for a running website is the least part of it. 

So if you want to help out, it'd be awesome to have someone that checks all the current entries and sees whether. those groups are still active. Or check whether there are details missing. Or find new usergroups. Or find a way to add the magento and wordpress usergroups that can be fetched via the Meetup-pro API but only with the master-admin key of magento or WordPress. Or provide a means of authenticating not only via Twitter but also via GitHub or something else (sane) so that chinese people behind the GCF can log into php.ug.

**Comment by TomasVotruba** [comment]
Well, my main goal is to have listed all European meetups, with CFP if possible. Nothing more.

I looked for such a tool and thought this is the one.

> So the website is not broken. It's that the usergroup didn't want to share that information.

I can see it on their website: http://www.bephpug.de/, they even have Github: https://github.com/berlinphp/berlinphp.github.com

I expect php.ug saves me time from checking every page manually.

Again, technically it might work, just not from the user point of view. Until that is fixed, I don't see meaning in other tasks.

Would you be open to move database to static files and generate all data on build? That way we'd have all the data in 1 place, fully open-source. Now I don't know what groups are added, which are outdated, how to rename them (e.g. there are 3 our old groups, that have completely new name and anyone looking for them in our country would find nothing, although we have 3 meetups a month) etc.

**Comment by heiglandreas** [comment]
What benefit would flat files provide against a database? People still need to ad the information and keep it up to date. And as long as we don't know about usergroups being closef or change name we can't adapt the infotmation. When every usergroup takes care of their own data everything is fine. Expecting "someone" to do that means a high probability for being out of date. 

So for a start it would be great to get the informations about those groups into php.ug. Feel free to use the promote-form at php.ug/promote tontell us about the new groups. Or bring the people in charge of the old groups to update their information. 

Feel free to use the API and I (and the whole PHP-community) will be thankfull for all feedback about european groups you can give back!

**Comment by TomasVotruba** [comment]
> What benefit would flat files provide against a database? People still need to ad the information and keep it up to date.

Open to edit, update... well the same open-source has to closed source :)l. Now it's closed source and I have to make many extra steps before I can even start working.

We use it in Pehapkari, here for lecture references: https://github.com/pehapkari/pehapkari.cz/tree/master/source/_data/lecture_references
an work pretty good.

I tried to use API, but failed on 2nd call, see: https://github.com/php-ug/php.ug/issues/211

**Comment by heiglandreas** [comment]
Interesting view. But I think you're mixing a few things up here.

Open Source means that you can *use* the data and are free to *modify your own copy* It does *not* mean that you are free to modify the original data. As you aren't with any sourcecode that is hosted on f.e. on GitHub. You can *use* it (if license permits) and do whatever you want with *your own fork* but the original author decides whether they accept a PullRequest to their data or not.

In terms of php.ug that means you can do whatever you want with the data stored in the database that you retrieved via the given API but you can not modify that data at your own will as it's not your data. It'S still the data that belongs, no, not to php.ug but to the usergroups. And that's why it's their responsibility to modify it. There are some moderators that will nudge usergroups but that'S a different story.

So comparing php.ug to closed source just because you can't modify the data at your own will is a very interesting concept…

**Comment by TomasVotruba** [comment]
> Open Source means that you can use the data and are free to modify your own copy It does not mean that you are free to modify the original data. As you aren't with any sourcecode that is hosted on f.e. on GitHub. You can use it (if license permits) and do whatever you want with your own fork but the original author decides whether they accept a PullRequest to their data or not.

I agree. I didn't mean that people will modify anything they want without your approval. I meant classic open source - everything is public and there is **an option** to send PR.
